/**
 * Software: LotteryAdvisor
 * Module: main class
 * Version: 0.1
 * Licence: GPL2
 * Owner: Kim Kristo
 * Date creation : 13.5.2010
 *
 */
package oh3ebf.lottery;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import oh3ebf.lottery.components.LotteryVisualInputDialog;
import oh3ebf.lottery.models.LotteryResultTableModel;
import org.apache.log4j.Logger;
import org.apache.log4j.BasicConfigurator;

public class LotteryAdvisor extends javax.swing.JFrame {

    private static final long serialVersionUID = 7526472295622776147L;
    private String game;
    private static Logger logger;
    private final LotteryResultTableModel lotteryResultModel;
    private static final int ID_COLUMN = 8;

    /**
     * Creates new form LotteryAdvisor
     */
    public LotteryAdvisor() {
        // get new logger instance
        logger = Logger.getLogger(LotteryAdvisor.class);
        // Set up a simple configuration that logs on the console.
        BasicConfigurator.configure();
        lotteryResultModel = new LotteryResultTableModel();

        initComponents();
        resultsTable.setModel(lotteryResultModel);
        resultsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        // hide id column
        resultsTable.getColumnModel().getColumn(ID_COLUMN).setMinWidth(0);
        resultsTable.getColumnModel().getColumn(ID_COLUMN).setMaxWidth(0);
        resultsTable.getColumnModel().getColumn(ID_COLUMN).setWidth(0);

        setLocationRelativeTo(null);
    }

    /**
     * Function translates string to object for combo boxes
     *
     * @param item string to convert
     *
     * @return Object for combo box item
     *
     */
    private Object makeObj(final String item) {
        return new Object() {
            @Override
            public String toString() {
                return item;
            }
        };
    }

    /**
     * Function clears playedDraw editing fields
     *
     */
    private void clearFields() {
        // clear edit fields
        veikkausIdTextField.setText("");
        brandNameTextField.setText("");
        closeTimeTextField.setText("");
        drawTimeTextField.setText("");
        primaryNumbersTextField.setText("");
        secondaryNumbersTextField.setText("");
    }

    /**
     * Function closes application
     *
     */
    public void exitKeno() {

        dispose();
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        secondaryNumbersTextField = new javax.swing.JTextField();
        closeTimeTextField = new javax.swing.JFormattedTextField();
        drawTimeTextField = new javax.swing.JFormattedTextField();
        brandNameTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        primaryNumbersTextField = new javax.swing.JTextField();
        veikkausIdTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clearFieldsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addDrawButton = new javax.swing.JButton();
        playedDrawsButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        gameComboBox = new javax.swing.JComboBox<>(lotteryResultModel.getGameNames().toArray());
        timeLineComboBox = new javax.swing.JComboBox<Object>();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<Object>();
        jComboBox2 = new javax.swing.JComboBox<Object>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<Object>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<Object>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SettingsMenuItem = new javax.swing.JMenuItem();
        AboutMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("oh3ebf/lottery/properties/Bundle"); // NOI18N
        setTitle(bundle.getString("Lottery.title")); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(640, 480));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(320, 220));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(520, 270));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(626, 120));
        jPanel10.setRequestFocusEnabled(false);

        jLabel17.setText(bundle.getString("Lottery.jLabel17.text")); // NOI18N

        jLabel16.setText(bundle.getString("Lottery.jLabel16.text")); // NOI18N

        jLabel15.setText(bundle.getString("Lottery.jLabel15.text")); // NOI18N

        veikkausIdTextField.setEditable(false);

        jLabel7.setText(bundle.getString("Lottery.jLabel7.text")); // NOI18N

        jLabel6.setText(bundle.getString("Lottery.jLabel6.text")); // NOI18N

        jLabel5.setText(bundle.getString("Lottery.jLabel5.text")); // NOI18N

        clearFieldsButton.setText(bundle.getString("Lottery.clearFieldsButton")); // NOI18N
        clearFieldsButton.setMinimumSize(new java.awt.Dimension(126, 25));
        clearFieldsButton.setPreferredSize(new java.awt.Dimension(126, 25));
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Status:");

        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addDrawButton.setText(bundle.getString("Lottery.addDrawButton")); // NOI18N
        addDrawButton.setEnabled(false);
        addDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrawButtonActionPerformed(evt);
            }
        });

        playedDrawsButton.setText(bundle.getString("Lottery.playedDrawsButton")); // NOI18N
        playedDrawsButton.setEnabled(false);
        playedDrawsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playedDrawsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondaryNumbersTextField)
                            .addComponent(primaryNumbersTextField)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brandNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(drawTimeTextField)
                                    .addComponent(closeTimeTextField)
                                    .addComponent(veikkausIdTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(clearFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDrawButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playedDrawsButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(veikkausIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(closeTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(drawTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(brandNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(primaryNumbersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(secondaryNumbersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDrawButton)
                    .addComponent(playedDrawsButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName(bundle.getString("Lottery.jLabel7.text")); // NOI18N

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setMinimumSize(new java.awt.Dimension(354, 50));
        jPanel11.setName(""); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(609, 50));

        jLabel13.setText(bundle.getString("Lottery.jLabel13.text")); // NOI18N
        jLabel13.setMinimumSize(new java.awt.Dimension(38, 23));
        jLabel13.setName(""); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(38, 23));

        gameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameComboBoxActionPerformed(evt);
            }
        });

        timeLineComboBox.setEnabled(false);
        timeLineComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeLineComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeLineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeLineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel7.add(jPanel11, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel7, java.awt.BorderLayout.NORTH);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(600, 700));
        jScrollPane3.setName(""); // NOI18N
        jScrollPane3.setOpaque(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(600, 700));

        resultsTable.setModel(lotteryResultModel);
        resultsTable.setFillsViewportHeight(true);
        resultsTable.setMaximumSize(new java.awt.Dimension(32767, 32767));
        resultsTable.setMinimumSize(new java.awt.Dimension(600, 700));
        resultsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resultsTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                resultsTableMouseDragged(evt);
            }
        });
        resultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(resultsTable);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(bundle.getString("Lottery.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setEnabled(false);
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        jComboBox2.setEnabled(false);
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, -1));

        jLabel3.setText(bundle.getString("Lottery.jLabel3.text")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(90, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(90, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 15));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText(bundle.getString("Lottery.jLabel4.text")); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel12.setText("testi");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jComboBox4.setEnabled(false);
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 100, -1));

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setDoubleBuffered(true);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jButton3.setText("Frekvenssi");
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(130, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(130, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(130, 25));
        jPanel5.add(jButton3);

        jButton4.setText("Yhteiset luvut");
        jButton4.setEnabled(false);
        jButton4.setMaximumSize(new java.awt.Dimension(130, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(130, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(130, 25));
        jButton4.setRequestFocusEnabled(false);
        jPanel5.add(jButton4);

        jPanel2.add(jPanel5, java.awt.BorderLayout.WEST);

        jTabbedPane1.addTab(bundle.getString("Lottery.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(520, 130));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText(bundle.getString("Lottery.jLabel8.text")); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel9.setText("Numerot:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButton5.setText("Lisää rivi");
        jButton5.setEnabled(false);
        jButton5.setMinimumSize(new java.awt.Dimension(126, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(126, 25));
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextField4.setEnabled(false);
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 440, -1));

        jComboBox3.setEnabled(false);
        jPanel6.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 120, -1));

        jLabel10.setText("Status:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 15, -1, -1));

        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 13, 80, 20));

        jButton7.setText("Tyhjennä");
        jButton7.setEnabled(false);
        jButton7.setMinimumSize(new java.awt.Dimension(126, 25));
        jButton7.setPreferredSize(new java.awt.Dimension(126, 25));
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jButton8.setText("Poista rivi");
        jButton8.setEnabled(false);
        jButton8.setMinimumSize(new java.awt.Dimension(126, 25));
        jButton8.setPreferredSize(new java.awt.Dimension(126, 25));
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addTab(bundle.getString("Lottery.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText(bundle.getString("Lottery.jMenu1.text")); // NOI18N

        SettingsMenuItem.setText(bundle.getString("Lottery.Setup.text")); // NOI18N
        SettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SettingsMenuItem);

        AboutMenuItem.setText(bundle.getString("Lottery.Info.text")); // NOI18N
        jMenu1.add(AboutMenuItem);

        ExitMenuItem.setText(bundle.getString("Lottery.Exit.text")); // NOI18N
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
        // update daytime field

    }


    private void resultsTableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseDragged
        // Function handles mouse dragging and clears selections

        // remove all selections
        resultsTable.clearSelection();

    }//GEN-LAST:event_resultsTableMouseDragged

    private void resultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseClicked
        // Function gets values to text fields for editing
        int row = resultsTable.getSelectedRow();

        // set selected values to text fields
        veikkausIdTextField.setText(resultsTable.getValueAt(row, 0).toString());

        brandNameTextField.setText(resultsTable.getValueAt(row, 2).toString());
        closeTimeTextField.setText(resultsTable.getValueAt(row, 3).toString());
        drawTimeTextField.setText(resultsTable.getValueAt(row, 4).toString());

        primaryNumbersTextField.setText(resultsTable.getValueAt(row, 5).toString());
        secondaryNumbersTextField.setText(resultsTable.getValueAt(row, 6).toString());

        playedDrawsButton.setEnabled(true);
    }//GEN-LAST:event_resultsTableMouseClicked

    private void SettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenuItemActionPerformed
        // open options dialog


    }//GEN-LAST:event_SettingsMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // close application
        exitKeno();
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void gameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameComboBoxActionPerformed
        // Function updates selection list for lottery round daily time
        clearFields();

        // check for validity
        if (gameComboBox.getSelectedItem() == null) {
            return;
        }

        game = gameComboBox.getSelectedItem().toString();

        lotteryResultModel.setPlay(game);
    }//GEN-LAST:event_gameComboBoxActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
        // Function clears text fields in arvonnat page
        clearFields();

        // remove all selections
        resultsTable.clearSelection();

        // disable played draws input dialog
        playedDrawsButton.setEnabled(false);
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void addDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrawButtonActionPerformed
        // Function handles new keno data insertion to database
        // Not Used any more

        int row = 0;
        boolean status = false;
        String round = veikkausIdTextField.getText();
        String date = closeTimeTextField.getText();
        String numbers = primaryNumbersTextField.getText();
        String game = gameComboBox.getSelectedItem().toString();

        try {
            // preferred date format
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

            // validate date string
            df.parse(date);
        } catch (Exception e) {
            System.out.println("Date parsing failure " + date);

            // set status indication
            jLabel1.setText(java.util.ResourceBundle.getBundle("keno/Bundle").getString("FAIL"));
            return;
        }

        // try to insert data to database
        if (round != "" && round.length() > 0 && date != "" && date.length() > 0 && numbers != "" && numbers.length() > 0) {
            // any existing values selected
            if ((row = resultsTable.getSelectedRow()) != -1) {
                /*try {
                 // update values
                 db.updateNumbers((Integer) resultsTable.getValueAt(row, 0), round, date, numbers);
                 status = true;
                 } catch (KenoException e) {

                 }*/
            } else {/*
                 // insert new values
                 try {
                 db.insertNumbers(game, round, date, numbers);
                 //if(db.insertNumbers(round, date, numbers) == true)
                 status = true;
                 } catch (KenoException e) {

                 }*/

            }

            if (status == true) {
                // set status indication
                //jLabel1.setBackground(green);
                jLabel1.setText(java.util.ResourceBundle.getBundle("keno/Bundle").getString("Keno.Ok.text"));

                // clear input fields
                veikkausIdTextField.setText("");
                closeTimeTextField.setText("");
                primaryNumbersTextField.setText("");

                // update new date values
                //initComboDateBox();
            } else {
                // set status indication
                jLabel1.setText(java.util.ResourceBundle.getBundle("keno/Bundle").getString("Keno.Fail.text"));
            }
        }
    }//GEN-LAST:event_addDrawButtonActionPerformed

    private void timeLineComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeLineComboBoxActionPerformed


    }//GEN-LAST:event_timeLineComboBoxActionPerformed

    private void playedDrawsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playedDrawsButtonActionPerformed
        int row = resultsTable.getSelectedRow();
        long id = (Long) resultsTable.getValueAt(row, ID_COLUMN);
        int game = gameComboBox.getSelectedIndex();

        LotteryVisualInputDialog dialog = new LotteryVisualInputDialog(this, true, game, id);

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_playedDrawsButtonActionPerformed

    /**
     * Main function
     *
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LotteryAdvisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem SettingsMenuItem;
    private javax.swing.JButton addDrawButton;
    private javax.swing.JTextField brandNameTextField;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JFormattedTextField closeTimeTextField;
    private javax.swing.JFormattedTextField drawTimeTextField;
    private javax.swing.JComboBox<Object> gameComboBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JComboBox<Object> jComboBox2;
    private javax.swing.JComboBox<Object> jComboBox3;
    private javax.swing.JComboBox<Object> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton playedDrawsButton;
    private javax.swing.JTextField primaryNumbersTextField;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextField secondaryNumbersTextField;
    private javax.swing.JComboBox<Object> timeLineComboBox;
    private javax.swing.JTextField veikkausIdTextField;
    // End of variables declaration//GEN-END:variables

}
