/**
 * Software: LotteryAdvisor
 * Module: LotteryVisualPlay class
 * Version: 0.1
 * Licence: GPL2
 * Owner: Kim Kristo
 * Date creation : 12.3.2012
 */
package oh3ebf.lottery.components;

import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import oh3ebf.lottery.components.events.LotteryVisualPlayEvent;
import oh3ebf.lottery.components.events.LotteryVisualPlayEventHandler;
import oh3ebf.lottery.models.LotteryVisualPlayModel;
import org.apache.log4j.Logger;

public class LotteryVisualInputDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 7526472295622776147L;
    private static Logger logger;
    private final List<LotteryVisualPlay> gameInputs;
    private LotteryVisualPlayModel playModel;
    private LotteryVisualPlayEventHandler events;

    /**
     * Creates new form LotteryVisualInputDialog
     *
     * @param parent
     * @param modal
     * @param game
     * @param lotteryId
     */
    public LotteryVisualInputDialog(java.awt.Frame parent, boolean modal, int game, long lotteryId) {
        super(parent, modal);
        GridLayout layout;

        // get logger instance for this class".
        logger = Logger.getLogger(LotteryVisualInputDialog.class);
        gameInputs = new ArrayList<>();
        events = new LotteryVisualPlayEventHandler();

        playModel = new LotteryVisualPlayModel();
        playModel.setPlayedDraw(lotteryId);

        initComponents();
        jList1.setModel(playModel);

        ResourceBundle bundle = ResourceBundle.getBundle("oh3ebf/lottery/properties/Bundle");
        
        switch (game) {
            case LotteryVisualPlay.LOTTO:
                // lotto 
                setTitle(bundle.getString("Lottery.LottoHeader"));
                setSize(990, 410);

                layout = (GridLayout) jPanel4.getLayout();
                layout.setRows(2);
                layout.setColumns(5);
                
                // add play boxes
                for (int i = 0; i < 12; i++) {
                    LotteryVisualPlay input = new LotteryVisualPlay(LotteryVisualPlay.LOTTO, i, playModel);

                    jPanel4.add(input);
                    gameInputs.add(input);
                    events.addLotteryVisialPlayListener(input);
                }
                break;
            case LotteryVisualPlay.VIKING_LOTTO:
                // viking lotto 
                setTitle(bundle.getString("Lottery.VikingLottoHeader"));
                setSize(950, 475);

                layout = (GridLayout) jPanel4.getLayout();
                layout.setRows(2);
                layout.setColumns(4);
                
                // add play boxes
                for (int i = 0; i < 8; i++) {
                    LotteryVisualPlay input = new LotteryVisualPlay(LotteryVisualPlay.VIKING_LOTTO, i, playModel);

                    jPanel4.add(input);
                    gameInputs.add(input);
                    events.addLotteryVisialPlayListener(input);
                }
                break;
            case LotteryVisualPlay.KENO:
                // keno 
                setTitle(bundle.getString("Lottery.KenoHeader"));
                setSize(850, 340);

                // add play boxes
                for (int i = 0; i < 5; i++) {
                    LotteryVisualPlay input = new LotteryVisualPlay(LotteryVisualPlay.KENO, i, playModel);

                    jPanel4.add(input);
                    gameInputs.add(input);
                    events.addLotteryVisialPlayListener(input);
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InputDialogCloseButton = new javax.swing.JButton();
        InputDialogApplyButton = new javax.swing.JButton();
        inputDialogNewButton = new javax.swing.JButton();
        resultsCheckBox = new javax.swing.JCheckBox();
        matchingResultCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KENO");
        setLocation(new java.awt.Point(0, 0));
        setModal(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 131));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setPreferredSize(new java.awt.Dimension(80, 85));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("oh3ebf/lottery/properties/Bundle"); // NOI18N
        InputDialogCloseButton.setText(bundle.getString("Lottery.InputDialogCloseButton")); // NOI18N
        InputDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDialogCloseButtonActionPerformed(evt);
            }
        });

        InputDialogApplyButton.setText(bundle.getString("Lottery.InputDialogApplyButton")); // NOI18N
        InputDialogApplyButton.setEnabled(false);
        InputDialogApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDialogApplyButtonActionPerformed(evt);
            }
        });

        inputDialogNewButton.setText(bundle.getString("Lottery.InputDialogNewButton")); // NOI18N
        inputDialogNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDialogNewButtonActionPerformed(evt);
            }
        });

        resultsCheckBox.setText(bundle.getString("Lottery.resultsCheckBox.text")); // NOI18N
        resultsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsCheckBoxActionPerformed(evt);
            }
        });

        matchingResultCheckBox.setText(bundle.getString("Lottery.matchingResultCheckBox.text")); // NOI18N
        matchingResultCheckBox.setEnabled(false);
        matchingResultCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchingResultCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(matchingResultCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(inputDialogNewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputDialogApplyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputDialogCloseButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultsCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputDialogCloseButton)
                            .addComponent(InputDialogApplyButton)
                            .addComponent(inputDialogNewButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultsCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matchingResultCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDialogCloseButtonActionPerformed
        // close dialog
        dispose();
    }//GEN-LAST:event_InputDialogCloseButtonActionPerformed

    private void InputDialogApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDialogApplyButtonActionPerformed
        // check for new play
        if (jList1.isSelectionEmpty()) {
            // tarvitanko päivityksessä listan id:tä???
        }

        // send event to save played numbers
        events.fireLotteryVisialPlayPersistEvent(new LotteryVisualPlayEvent());
        
        // update played games list
        playModel.refresh();
    }//GEN-LAST:event_InputDialogApplyButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (!evt.getValueIsAdjusting()) {
            logger.info("selection " + jList1.getSelectedValue());
            playModel.setTicketName(jList1.getSelectedValue());

            // enable check boxes
            matchingResultCheckBox.setEnabled(true);
            //resultsCheckBox.setEnabled(true);

            // send event to show played numbers
            events.fireLotteryVisialPlaySelectionEvent(new LotteryVisualPlayEvent());
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void resultsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsCheckBoxActionPerformed
        // 

        LotteryVisualPlayEvent event = new LotteryVisualPlayEvent();

        event.setState(resultsCheckBox.isSelected());
        // send event to show drawn numbers
        events.fireLotteryVisialPlayDrawnNumbersEvent(event);
    }//GEN-LAST:event_resultsCheckBoxActionPerformed

    private void matchingResultCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchingResultCheckBoxActionPerformed
        // 

        LotteryVisualPlayEvent event = new LotteryVisualPlayEvent();

        event.setState(matchingResultCheckBox.isSelected());

        // send event to calculate matching numbers
        events.fireLotteryVisialPlayMatchingResultEvent(event);
    }//GEN-LAST:event_matchingResultCheckBoxActionPerformed

    private void inputDialogNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDialogNewButtonActionPerformed
        // clear current selection if any
        jList1.clearSelection();

        Date date = new Date();
        String datePrefix = new SimpleDateFormat("dd.MM.yyyy").format(date);
        playModel.setTicketName(datePrefix + "-" + (playModel.getSize() + 1));

        // send event to clear played numbers
        events.fireLotteryVisialPlayClearDataEvent(new LotteryVisualPlayEvent());
        // enable game storing
        InputDialogApplyButton.setEnabled(true);
    }//GEN-LAST:event_inputDialogNewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InputDialogApplyButton;
    private javax.swing.JButton InputDialogCloseButton;
    private javax.swing.JButton inputDialogNewButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox matchingResultCheckBox;
    private javax.swing.JCheckBox resultsCheckBox;
    // End of variables declaration//GEN-END:variables

}
